spring:
 h2:
  console:
    enabled: true
    path: /h2-console
datasourse:
 driver-class-name: org.h2.Driver
 url: jdbc:h2:~/users
 username: sa
 password: 1111
jpa:
   properties:
    hibernate:
     format_sql: true
     show_sql: true
   show-sql: true
   hibernate:
    ddl-auto: create
logging:
 level:
  org:
   hibernate:
    SQL: debug
    orm:
     jdbc:
      bind: trace
   springframework: # ??!
    security: debug # ??!
auth:
  jwt:
    issuer: team.100days.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 168